/*
 * Thumbnail resolution for Life Admin categories & subcategories.
 *
 * Files live in public/thumbnails/{categories,subcategories}/<id>.png,
 * generated by scripts/generate-thumbnails.ts. This helper resolves the
 * best available thumbnail URL with sensible fallbacks so components
 * don't need to know which files exist.
 */

import { existsSync } from "node:fs";
import { resolve } from "node:path";
import type { CategoryId } from "@/lib/db/types";

const PUBLIC_ROOT = resolve(process.cwd(), "public");

function fileExists(relPath: string): boolean {
  try {
    return existsSync(resolve(PUBLIC_ROOT, relPath));
  } catch {
    return false;
  }
}

export function categoryThumbnail(categoryId: CategoryId): string {
  return `/thumbnails/categories/${categoryId}.png`;
}

/**
 * Returns a subcategory thumbnail URL if one has been generated,
 * else falls back to the category thumbnail. Safe to call from server
 * components — checks the filesystem synchronously against the public
 * directory.
 */
export function subcategoryThumbnail(
  subcategoryId: string,
  categoryId: CategoryId
): string {
  const rel = `thumbnails/subcategories/${subcategoryId}.png`;
  if (fileExists(rel)) return `/${rel}`;
  return categoryThumbnail(categoryId);
}

export type DashboardThumbnailId =
  | "records-documents"
  | "expiring-soon"
  | "tasks"
  | "all-good"
  | "add-record"
  | "upload-document"
  | "scan-document"
  | "add-reminder";

export function dashboardThumbnail(id: DashboardThumbnailId): string {
  return `/thumbnails/dashboard/${id}.png`;
}
