// Curated subject prompts for every Life Admin subcategory.
// Consumed by scripts/generate-thumbnails.ts. The subject is fed into a
// standard brand prompt so every image feels consistent.
//
// "Other" catch-alls (personal.other, admin.other, education.other,
// employment.other) are omitted — they fall back to the category thumbnail.
// User-created subcategories (personal.custom_*) are never pre-generated;
// they always fall back to the category.

export interface SubcategoryPrompt {
  id: string;
  subject: string;
}

export const SUBCATEGORY_PROMPTS: readonly SubcategoryPrompt[] = [
  // ── Personal ────────────────────────────────────────────────────────────
  { id: "personal.emergency_contacts",
    subject: "a warm illustrated phone handset and a small notebook opened to a page of neatly written contact names" },
  { id: "personal.general_information",
    subject: "a single-page personal information form on a wooden desk, with a fountain pen resting beside it" },
  { id: "personal.birth_certificates",
    subject: "an official birth certificate with a decorative border and a red ribbon seal in the corner" },
  { id: "personal.marriage_certificate",
    subject: "a folded marriage certificate scroll tied with a delicate silk ribbon" },
  { id: "personal.passport_travel",
    subject: "a passport lying open on top of two boarding passes and a small folded map" },
  { id: "personal.will_funeral",
    subject: "a formal sealed envelope with a wax seal, resting on top of a leather-bound folder" },
  { id: "personal.power_of_attorney",
    subject: "a legal document with a formal signature line and a fountain pen laid across the signature area" },
  { id: "personal.advanced_health_directive",
    subject: "a clipboard holding a medical directive form and a small red heart symbol in the corner" },
  { id: "personal.electoral_roll",
    subject: "a ballot slip going into a wooden ballot box beside a small envelope" },
  { id: "personal.tax_file_number",
    subject: "an Australian Tax File Number letter partially folded, with a paperclip attached" },
  { id: "personal.abn",
    subject: "a small business registration certificate leaning next to a stamp and ink pad" },
  { id: "personal.list_of_accounts",
    subject: "a paper checklist of website names beside a small padlock and a house key" },
  { id: "personal.licences_ids",
    subject: "a driver's licence card overlapping a photo id card, stacked at a slight angle" },
  { id: "personal.vehicle_details",
    subject: "a car registration certificate folded once, beside a small stylised car key with a keyring tag" },
  { id: "personal.accident_information",
    subject: "an accident report form on a clipboard next to a small warning triangle icon" },
  { id: "personal.home_property_rates_rent",
    subject: "a small stylised house with a paper rates notice tucked under the front door" },
  { id: "personal.daily_routine_planner",
    subject: "an open daily planner notebook with a coffee cup and a small alarm clock beside it" },
  { id: "personal.family_contacts",
    subject: "a paper address book open to a page titled 'family', with soft heart accents" },
  { id: "personal.friends_contacts",
    subject: "a paper address book open to a page titled 'friends', with speech-bubble accents" },
  { id: "personal.other_contacts",
    subject: "a rolodex-style contact card stack with a small pin sticking out of the top card" },
  { id: "personal.device_access",
    subject: "a smartphone and a laptop side by side with a small stylised key floating between them" },
  { id: "personal.important_documents_register",
    subject: "a paper index list on a clipboard with tabbed dividers running down the side" },
  { id: "personal.end_of_life_wishes",
    subject: "a handwritten letter partly rolled up, with a candle beside it and a pressed flower" },
  { id: "personal.legacy_letters",
    subject: "a stack of sealed envelopes tied together with twine, ready to be handed on" },

  // ── Health ──────────────────────────────────────────────────────────────
  { id: "health.medical_advisers",
    subject: "a paper directory list of doctors' names on a clipboard beside a stethoscope" },
  { id: "health.medication_list",
    subject: "three amber pill bottles arranged in a row with a small pill organiser beside them" },
  { id: "health.health_insurance_cards",
    subject: "an Australian medicare-style health card and a private health insurance card stacked" },
  { id: "health.concession_cards",
    subject: "a stylised concession card with a subtle discount symbol in the corner" },
  { id: "health.pension_cards",
    subject: "a formal pension card with an official crest, lying on a wooden surface" },
  { id: "health.health_insurance",
    subject: "a folded health insurance policy document with a small first aid cross icon" },
  { id: "health.life_insurance",
    subject: "a life insurance policy folded once, with a small stylised umbrella sheltering a heart" },
  { id: "health.my_health_plan",
    subject: "an open personal health plan notebook with tick-boxes and a small water bottle beside it" },
  { id: "health.dental_records",
    subject: "a paper dental chart with a small stylised toothbrush and toothpaste tube" },
  { id: "health.scripts",
    subject: "a doctor's prescription paper folded once, with a small pill capsule and pen" },
  { id: "health.blood_tests",
    subject: "a small labelled test tube and a paper results sheet with a subtle line chart" },
  { id: "health.specialist_reports",
    subject: "a folded medical report bearing a small caduceus symbol in the corner" },
  { id: "health.referrals",
    subject: "a paper referral letter tucked into an envelope, with a small arrow shape hinting at direction" },
  { id: "health.hospital_discharge",
    subject: "a hospital discharge paper on a clipboard beside a small hospital-building icon" },
  { id: "health.medical_reports",
    subject: "a folder tab labelled 'medical' with a stethoscope curling around it" },
  { id: "health.medical_bills",
    subject: "a medical invoice with an itemised list beside a small stack of coins" },
  { id: "health.meal_planning",
    subject: "a weekly meal-plan grid on paper beside a small basket of vegetables" },
  { id: "health.favourite_recipes",
    subject: "an open recipe book with a wooden spoon resting across the pages" },
  { id: "health.life_goals_plans",
    subject: "a small vision board with pinned notes and a stylised mountain with a flag on top" },
  { id: "health.mind_set",
    subject: "an illustrated brain shape overlaid with a soft lotus flower and a gentle sun ray" },
  { id: "health.retirement_pension",
    subject: "a piggy bank next to a folded retirement plan document and a small sailboat" },

  // ── Education ───────────────────────────────────────────────────────────
  { id: "education.courses_enrolment",
    subject: "an enrolment form on a clipboard beside a fresh yellow pencil and eraser" },
  { id: "education.enrolment_documents",
    subject: "a stack of enrolment paperwork clipped together, with a school-crest sticker on top" },
  { id: "education.primary_details",
    subject: "a small primary-school report card beside a wax crayon and a gold star sticker" },
  { id: "education.secondary_details",
    subject: "a high-school transcript document beside a scientific calculator and a compass" },
  { id: "education.tertiary_details",
    subject: "a university transcript with a graduation cap perched on top and a rolled diploma" },
  { id: "education.other_courses_details",
    subject: "a certificate of completion with a printed course name and a decorative ribbon" },
  { id: "education.achievement_certificates",
    subject: "an achievement certificate with a gold seal and a first-place ribbon beside it" },
  { id: "education.study_plan",
    subject: "a weekly study planner grid on paper with a highlighter and sticky note tabs" },
  { id: "education.course_storage",
    subject: "a neat row of labelled folders on a bookshelf, each with a subject title on its spine" },

  // ── Employment ──────────────────────────────────────────────────────────
  { id: "employment.employee_information_form",
    subject: "a new-starter form on a clipboard beside a company id lanyard" },
  { id: "employment.cover_letter",
    subject: "a folded cover letter document with a fountain pen and a stamped envelope" },
  { id: "employment.resume",
    subject: "a printed resume document with a photo placeholder and a paperclip attached" },
  { id: "employment.letters_of_recommendation",
    subject: "two sealed formal envelopes stamped with a wax seal, one on top of the other" },
  { id: "employment.volunteering_certificates",
    subject: "a certificate of volunteering with two hands offering a small heart" },
  { id: "employment.employee_contracts",
    subject: "a bound employment contract booklet with a signature line and a fountain pen" },
  { id: "employment.job_description",
    subject: "a job description page on a clipboard with bullet points and a small tie icon" },
  { id: "employment.employment_reviews",
    subject: "a performance review form with a five-star row and a small pencil resting on it" },
  { id: "employment.correspondence",
    subject: "a small stack of workplace letters bound with a rubber band" },
  { id: "employment.wages_summaries",
    subject: "a payslip with printed amounts beside a small stack of coins and a folded banknote" },
  { id: "employment.annual_payment_summary",
    subject: "an annual payment summary letter partly unfolded with a subtle graph in the corner" },

  // ── Admin & Bookkeeping ─────────────────────────────────────────────────
  { id: "admin.bank_accounts_advisers",
    subject: "a paper list of bank names beside a small stylised bank building with columns" },
  { id: "admin.bank_statements",
    subject: "a monthly bank statement with a neat table and a small piggy bank beside it" },
  { id: "admin.loan_statements",
    subject: "a loan statement document with a small stylised handshake in the corner" },
  { id: "admin.budgets",
    subject: "a household budget spreadsheet on paper with a calculator and a pen resting on it" },
  { id: "admin.investments_deeds",
    subject: "a formal investment deed rolled up with a red ribbon beside a small growing plant" },
  { id: "admin.super_statements",
    subject: "a superannuation statement folded once with a small piggy bank with a wing icon" },
  { id: "admin.property_records",
    subject: "a stylised house with a set of property title deeds folded neatly beside it" },
  { id: "admin.annual_tax_report",
    subject: "an annual tax return folder with a printed sum total and a receipt underneath" },
  { id: "admin.tax_payment_plans",
    subject: "a calendar page with instalment amounts marked and a small pen circling one" },
  { id: "admin.home_insurance",
    subject: "a stylised house sheltered beneath an umbrella, with a policy document beside it" },
  { id: "admin.other_business_insurance",
    subject: "a small factory-shaped building sheltered beneath an umbrella with a policy document" },
  { id: "admin.vehicle_insurance",
    subject: "a small car sheltered beneath an umbrella with a folded insurance policy" },
  { id: "admin.telephone_devices",
    subject: "a smartphone and an old rotary telephone side by side with a paper contract underneath" },
  { id: "admin.electricity_gas",
    subject: "a paper utilities bill with a small light bulb and a gas flame icon in the corner" },
  { id: "admin.rates_water",
    subject: "a council rates notice folded once, beside a small stylised water tap dripping a drop" },
  { id: "admin.rental_agreements",
    subject: "a bound rental lease booklet with two keys resting on top" },
  { id: "admin.warranties",
    subject: "a stack of appliance warranty cards fanned out with a small toolbox behind them" },
  { id: "admin.invoices_jul_jun",
    subject: "a monthly folder tab labelled with the fiscal year, holding a small stack of receipts" },
  { id: "admin.accountants",
    subject: "a paper list of accountant names with a calculator beside it and a pen resting on top" },
  { id: "admin.loans_register",
    subject: "a hand-written ledger book open to a page titled 'loans', with a magnifying glass beside it" },
];
